#!/usr/bin/env python3
"""
Parses Slang-generated .metal files and emits a C++ header with binding constants.
Run this after shader compilation and before C++ compilation.
"""
import argparse
import os
import re
import sys

KERNEL_RE = re.compile(
    r'\[\[kernel\]\]\s+void\s+(\w+)\s*\('
)

BINDING_RE = re.compile(r'(\w+)\s*\[\[(texture|buffer|sampler)\((\d+)\)\]\]')

def strip_numeric_suffix(name):
    """Strip trailing _N suffix added by Slang (e.g. texDirectLight_1 -> texDirectLight)."""
    return re.sub(r'_\d+$', '', name)

def parse_metal_file(filepath):
    with open(filepath, 'r') as f:
        content = f.read()
    
    # Find kernel function signature
    match = KERNEL_RE.search(content)
    if not match:
        return None
    
    kernel_name = match.group(1)
    
    # Extract the full parameter list by finding the matching )
    start = match.start()
    paren_open = content.find('(', start)
    
    # Simple paren matching
    depth = 0
    paren_close = paren_open
    for i in range(paren_open, len(content)):
        if content[i] == '(':
            depth += 1
        elif content[i] == ')':
            depth -= 1
            if depth == 0:
                paren_close = i
                break
    
    param_list = content[paren_open+1:paren_close]
    
    bindings = {
        'texture': {},
        'buffer': {},
        'sampler': {},
    }
    
    for m in BINDING_RE.finditer(param_list):
        param_name = strip_numeric_suffix(m.group(1))
        binding_type = m.group(2)
        binding_index = int(m.group(3))
        bindings[binding_type][param_name] = binding_index
    
    return kernel_name, bindings

def generate_header(parsed_kernels):
    lines = []
    lines.append('// Auto-generated by gen_shader_bindings.py')
    lines.append('// Do not edit manually. Regenerate after shader changes.')
    lines.append('#pragma once')
    lines.append('#include <cstdint>')
    lines.append('')
    lines.append('namespace ShaderBindings {')
    lines.append('')
    
    for kernel_name, bindings in sorted(parsed_kernels.items()):
        lines.append(f'namespace {kernel_name} ' + '{')
        
        for binding_type in ['texture', 'buffer', 'sampler']:
            items = bindings.get(binding_type, {})
            if not items:
                continue
            lines.append(f'    namespace {binding_type} ' + '{')
            for param_name in sorted(items.keys()):
                idx = items[param_name]
                lines.append(f'        constexpr uint32_t {param_name} = {idx};')
            lines.append('    }')
        
        lines.append('}')
        lines.append('')
    
    lines.append('} // namespace ShaderBindings')
    lines.append('')
    return '\n'.join(lines)

def main():
    parser = argparse.ArgumentParser(description='Generate shader binding constants from .metal files')
    parser.add_argument('input_dir', help='Directory containing generated .metal files')
    parser.add_argument('output', help='Output header file path')
    args = parser.parse_args()
    
    parsed = {}
    for filename in sorted(os.listdir(args.input_dir)):
        if not filename.endswith('.metal'):
            continue
        filepath = os.path.join(args.input_dir, filename)
        result = parse_metal_file(filepath)
        if result:
            kernel_name, bindings = result
            parsed[kernel_name] = bindings
    
    if not parsed:
        print('No kernels found.', file=sys.stderr)
        sys.exit(1)
    
    header = generate_header(parsed)
    
    # Only write if changed to avoid unnecessary rebuilds
    if os.path.exists(args.output):
        with open(args.output, 'r') as f:
            if f.read() == header:
                print(f'Bindings unchanged: {args.output}')
                return
    
    out_dir = os.path.dirname(args.output)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(args.output, 'w') as f:
        f.write(header)
    
    print(f'Generated: {args.output} ({len(parsed)} kernels)')

if __name__ == '__main__':
    main()
